CREATE TABLE Personal_information (
  personalNum NUMBER PRIMARY KEY,
  placeBirth VARCHAR2(25),
  passport VARCHAR2(30),
  address VARCHAR2(50),
  regAddress VARCHAR2(50),
  maritalStat VARCHAR2(20),
  children NUMBER,
  dateBirth VARCHAR2(50)
);

CREATE TABLE Department (
  idDep NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  department VARCHAR2(50),
  leader VARCHAR2(50),
  phoneNum VARCHAR2(20),
  location SDO_GEOMETRY
);

CREATE TABLE Official_information (
  idEmployee NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  personalNum NUMBER,
  surname VARCHAR2(50),
  name VARCHAR2(50),
  patronymic VARCHAR2(50),
  idDep NUMBER,
  education VARCHAR2(50),
  experience VARCHAR2(50),
  phoneNum VARCHAR2(20),
  salary NUMBER,
  status VARCHAR2(20),
  CONSTRAINT personalNum_FK FOREIGN KEY (personalNum) REFERENCES Personal_information (personalNum),
  CONSTRAINT idDep_ofInf_FK FOREIGN KEY (idDep) REFERENCES Department (idDep)
);

CREATE TABLE Vacancy (
  idVacancy NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  idDep NUMBER,
  salary NUMBER,
  status VARCHAR2(18) NOT NULL CHECK (status IN ('Доступно', 'Не доступно')),
  CONSTRAINT idDep_vac_FK FOREIGN KEY (idDep) REFERENCES Department (idDep)
);
